version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest-asyncio
    versions:
    - 0.15.0
  - dependency-name: discord-py
    versions:
    - 1.7.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: docker
  directory: "/"
  shcedule:
    interval: weekly
