name: Master Workflow
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened ]
    branches:
      - master
jobs:
  build:
    name: Build python environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install requirements
        run: pip install -r ./requirements.txt
      - name: Run main.py
        run: python ./main.py
      - name: Run test
        run: pytest
